-- Personal (Davide) — clienti + fatture personali, separate dal CRM
CREATE TABLE IF NOT EXISTS personal_clients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  address TEXT NULL,
  piva VARCHAR(191) NULL,
  cf VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  INDEX idx_personal_clients_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS personal_invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_number VARCHAR(191) NOT NULL UNIQUE,
  personal_client_id INT NULL,
  client_name VARCHAR(191) NOT NULL,
  client_address TEXT NULL,
  client_piva VARCHAR(191) NULL,
  client_cf VARCHAR(191) NULL,
  subject VARCHAR(191) NOT NULL,
  description TEXT NULL,
  quantity DOUBLE NOT NULL DEFAULT 1.00,
  unit_price DOUBLE NOT NULL,
  subtotal DOUBLE NOT NULL,
  vat_percentage DOUBLE NOT NULL DEFAULT 0,
  vat_amount DOUBLE NOT NULL,
  total DOUBLE NOT NULL,
  issue_date DATETIME(3) NOT NULL,
  due_date DATETIME(3) NOT NULL,
  payment_days INT NOT NULL DEFAULT 30,
  status ENUM('DRAFT','ISSUED','PAID','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  payment_date DATETIME(3) NULL,
  payment_method VARCHAR(191) NULL,
  payment_notes TEXT NULL,
  tax_reserved TINYINT(1) NOT NULL DEFAULT 0,
  tax_amount DOUBLE NULL,
  electronic_invoice_number VARCHAR(191) NULL,
  fiscal_notes TEXT NULL,
  pdf_path VARCHAR(191) NULL,
  pdf_generated_at DATETIME(3) NULL,
  created_by INT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  INDEX idx_personal_invoices_invoice_number (invoice_number),
  INDEX idx_personal_invoices_issue_date (issue_date),
  INDEX idx_personal_invoices_status (status),
  INDEX idx_personal_invoices_personal_client_id (personal_client_id),
  INDEX idx_personal_invoices_created_by (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
